/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import logika.KlijentKontroler;
import domen.Projekat;
import domen.Zaposleni;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modeli_tabela.ProjektiTableModel;
import forme_projekat.*;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ListSelectionModel;
import komunikacija.util.Operacija;

/**
 *
 * @author relja
 */
public class PocetnaForma extends javax.swing.JFrame {

    /**
     * Creates new form PocetnaForma
     */
    Zaposleni zaposleni;
    List<Projekat> projekti;
    ProjektiTableModel ptm;

    public PocetnaForma() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        try {
            this.zaposleni = KlijentKontroler.getInstance().getZaposleni();
        } catch (IOException ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        popuniKomponente();
        podesiLogoutNaExit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtImeKompanije = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPIB = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDrzava = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGrad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDatumOsnivanja = new javax.swing.JTextField();
        lblBrojTrenutnoZaposlenih = new javax.swing.JLabel();
        lblBrojAktivnihProjekata = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtImePrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtJMBG = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUloga = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        comboElementPretrage = new javax.swing.JComboBox<>();
        btnPrikaziSve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaProjekata = new javax.swing.JTable();
        btnKreirajNoviProjekat = new javax.swing.JButton();
        btnUcitajProjekat = new javax.swing.JButton();
        btnObrisiProjekat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pocetna forma");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacije o kompaniji"));
        jPanel1.setToolTipText("");

        jLabel3.setText("Ime kompanije: ");

        txtImeKompanije.setEditable(false);

        jLabel4.setText("Poreski identifikacioni broj: ");

        txtPIB.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sedište kompanije"));

        jLabel5.setText("Država: ");

        txtDrzava.setEditable(false);

        jLabel6.setText("Grad:");

        txtGrad.setEditable(false);
        txtGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradActionPerformed(evt);
            }
        });

        jLabel7.setText("Datum osnivanja: ");

        txtDatumOsnivanja.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(txtDatumOsnivanja, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDrzava, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDatumOsnivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBrojTrenutnoZaposlenih.setText("Broj trenutno zaposlenih: ");

        lblBrojAktivnihProjekata.setText("Broj aktivnih projekata: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImeKompanije, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrojTrenutnoZaposlenih)
                            .addComponent(lblBrojAktivnihProjekata))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtImeKompanije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblBrojTrenutnoZaposlenih)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBrojAktivnihProjekata)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Trenutni korisnik sistema"));

        jLabel1.setText("Ime i prezime: ");

        txtImePrezime.setEditable(false);

        jLabel2.setText("Korisnicko ime:");

        txtKorisnickoIme.setEditable(false);

        jLabel10.setText("JMBG:");

        txtJMBG.setEditable(false);

        jLabel8.setText("Uloga: ");

        txtUloga.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtUloga, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtUloga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Aktivni projekti"));

        btnPretrazi.setText("Pretrazi projekte po");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        comboElementPretrage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nazivu", "Opisu", "ID-u", "Datumu pocetka" }));
        comboElementPretrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboElementPretrageActionPerformed(evt);
            }
        });

        btnPrikaziSve.setText("Prikazi sve projekte");
        btnPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSveActionPerformed(evt);
            }
        });

        tblTabelaProjekata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Naziv", "Opis", "Datum pocetka"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaProjekata);

        btnKreirajNoviProjekat.setText("Kreiraj novi projekat");
        btnKreirajNoviProjekat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajNoviProjekatActionPerformed(evt);
            }
        });

        btnUcitajProjekat.setText("Ucitaj projekat");
        btnUcitajProjekat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajProjekatActionPerformed(evt);
            }
        });

        btnObrisiProjekat.setText("Obrisi projekat");
        btnObrisiProjekat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiProjekatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnKreirajNoviProjekat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUcitajProjekat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiProjekat))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboElementPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrikaziSve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(comboElementPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikaziSve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajNoviProjekat)
                    .addComponent(btnUcitajProjekat)
                    .addComponent(btnObrisiProjekat))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        Projekat projekatZaPretragu = new Projekat();
        projekatZaPretragu.setKompanija(this.zaposleni.getKompanija());
        
        String vrednostZaPretragu = txtPretraga.getText();
        String atributPretrage = comboElementPretrage.getItemAt(comboElementPretrage.getSelectedIndex());

        if (vrednostZaPretragu == null || vrednostZaPretragu.equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti vrednost za pretragu!", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        switch (atributPretrage) {
            case "Nazivu" ->
                projekatZaPretragu.setNaziv(vrednostZaPretragu);
            case "Opisu" ->
                projekatZaPretragu.setOpis(vrednostZaPretragu);
            case "ID-u" -> {
                try {
                    projekatZaPretragu.setIdProjekat(Integer.parseInt(vrednostZaPretragu));
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Pogresan unos! Niste uneli celobrojnu vrednost!", "Greska!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            case "Datumu pocetka" -> {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                try {
                    LocalDate date = LocalDate.parse(vrednostZaPretragu, formatter);
                    projekatZaPretragu.setDatumPocetka(date);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Pogresan unos! Niste uneli datum u trazenom formatu (YYYY-MM-DD).", "Greska!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }

        try {
            projekti = KlijentKontroler.getInstance().pretraziProjekte(projekatZaPretragu);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        ptm = new ProjektiTableModel(projekti);

        if (projekti == null || projekti.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze naci projekte po zadatoj vrednosti!", "Greska!", JOptionPane.ERROR_MESSAGE);
        } else {
            tblTabelaProjekata.setModel(ptm);
            JOptionPane.showMessageDialog(this, "Sistem je pronasao projekte po zadatoj vrednosti!", "Uspesna pretraga!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnUcitajProjekatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajProjekatActionPerformed
        int obelezenRed = tblTabelaProjekata.getSelectedRow();

        if (obelezenRed != -1) {
            try {
                Projekat ucitanProjekat = KlijentKontroler.getInstance().ucitajProjekat(projekti.get(obelezenRed));
                new FormaProjekat(ucitanProjekat, this);
            } catch (Exception ex) {
                Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nije izabran nijedan red!", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUcitajProjekatActionPerformed

    private void btnKreirajNoviProjekatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajNoviProjekatActionPerformed
        new FormaKreiranjeProjekta(this, this.zaposleni);
    }//GEN-LAST:event_btnKreirajNoviProjekatActionPerformed

    private void comboElementPretrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboElementPretrageActionPerformed
        txtPretraga.setToolTipText(null);
        if (comboElementPretrage.getSelectedItem().equals("Datumu pocetka")) {
            txtPretraga.setToolTipText("Unesi datum u formatu \"YYYY-MM-DD\"");
        }
    }//GEN-LAST:event_comboElementPretrageActionPerformed

    private void btnPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSveActionPerformed
        popuniKomponente();
        txtPretraga.setText("");
    }//GEN-LAST:event_btnPrikaziSveActionPerformed

    private void txtGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradActionPerformed

    private void btnObrisiProjekatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiProjekatActionPerformed
        int obelezenRed = tblTabelaProjekata.getSelectedRow();
        if (obelezenRed == -1) {
            JOptionPane.showMessageDialog(this, "Nije izabran nijedan red!", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Projekat projekat = projekti.get(obelezenRed);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        try {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Da li stvarno želite obrisati projekat: " + projekat + "?", "Upozorenje", dialogButton, JOptionPane.WARNING_MESSAGE);
            if (dialogResult == JOptionPane.YES_OPTION) {
                KlijentKontroler.getInstance().obrisiProjekat(projekat);
                popuniTabelu();
                JOptionPane.showMessageDialog(this, "Uspesno obrisan projekat: " + projekat + "!", "Informacija", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja projekta: " + projekat + "!", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja projekta: " + projekat + "!", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnObrisiProjekatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajNoviProjekat;
    private javax.swing.JButton btnObrisiProjekat;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziSve;
    private javax.swing.JButton btnUcitajProjekat;
    private javax.swing.JComboBox<String> comboElementPretrage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojAktivnihProjekata;
    private javax.swing.JLabel lblBrojTrenutnoZaposlenih;
    private javax.swing.JTable tblTabelaProjekata;
    private javax.swing.JTextField txtDatumOsnivanja;
    private javax.swing.JTextField txtDrzava;
    private javax.swing.JTextField txtGrad;
    private javax.swing.JTextField txtImeKompanije;
    private javax.swing.JTextField txtImePrezime;
    private javax.swing.JTextField txtJMBG;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtPIB;
    private javax.swing.JTextField txtPretraga;
    private javax.swing.JTextField txtUloga;
    // End of variables declaration//GEN-END:variables

    public void popuniKomponente() {
        txtImePrezime.setText(zaposleni.getImePrezime());
        txtImeKompanije.setText(zaposleni.getKompanija().getNazivKompanije());
        txtKorisnickoIme.setText(zaposleni.getKorisnickoIme());
        txtJMBG.setText(zaposleni.getJMBG());
        txtDrzava.setText(zaposleni.getKompanija().getDrzava());
        txtGrad.setText(zaposleni.getKompanija().getGrad());
        txtDatumOsnivanja.setText(zaposleni.getKompanija().getDatumOsnivanja().toString());
        txtPIB.setText(zaposleni.getKompanija().getPIB());
        txtUloga.setText(zaposleni.getUloga().getNaziv());

        podesiStanjaUOdnosuNaDozvole();
        
        try {
            List<Zaposleni> zaposleni = KlijentKontroler.getInstance().vratiListuSvihZaposlenih(this.zaposleni);
            int brojZaposlenih = zaposleni.size();
            lblBrojTrenutnoZaposlenih.setText("Broj trenutno zaposlenih: " + String.valueOf(brojZaposlenih));
        } catch (IOException ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            System.out.println("Neuspesno ucitavajne zaposlenih!");
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        popuniTabelu();

        comboElementPretrage.addActionListener((ActionEvent e) -> {
            txtPretraga.setText("");
        });

    }
    
    private void podesiStanjaUOdnosuNaDozvole() {
            if (!this.zaposleni.imaDozvolu(Operacija.ZAPAMTI_PROJEKAT)) {
                btnKreirajNoviProjekat.setEnabled(false);
            }
            if (!this.zaposleni.imaDozvolu(Operacija.OBRISI_PROJEKAT)){
                btnObrisiProjekat.setEnabled(false);
            }
    }

    public void popuniTabelu() {
        try {
            Projekat projekat = new Projekat();
            projekat.setKompanija(this.zaposleni.getKompanija());
            projekti = KlijentKontroler.getInstance().vratiListuSvihProjekata(projekat);

            int brojProjekata = projekti.size();
            lblBrojAktivnihProjekata.setText("Broj aktivnih projekata: " + String.valueOf(brojProjekata));

            ptm = new ProjektiTableModel(projekti);
            tblTabelaProjekata.setModel(ptm);

            tblTabelaProjekata.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void podesiLogoutNaExit() {
        WindowListener exitListener = new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                int confirm = JOptionPane.showOptionDialog(
                        null, "Da li stvarno želite da izađete iz aplikacije?",
                        "Upozorenje", JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE, null, null, null);
                if (confirm == 0) {
                    try {
                        KlijentKontroler.getInstance().logout();
                    } catch (IOException ex) {
                        Logger.getLogger(PocetnaForma.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    System.exit(0);
                }
            }
        };
        this.addWindowListener(exitListener);
    }

}
