/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme_zadatak;

import logika.KlijentKontroler;
import domen.Projekat;
import domen.Zadatak;
import forme_projekat.FormaProjekat;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author relja
 */
public class FormaKreiranjeZadatka extends javax.swing.JFrame {

    /**
     * Creates new form FormaKreiranjeZadatka
     */
    Projekat projekat;
    FormaProjekat parentForma;

    public FormaKreiranjeZadatka(Projekat projekat, FormaProjekat parentForma) {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        areaOpis.setLineWrap(true);
        areaOpis.setWrapStyleWord(true);
        this.projekat = projekat;
        this.parentForma = parentForma;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOpis = new javax.swing.JTextArea();
        btnKreirajZadatak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dodavanje zadatka");

        jLabel1.setText("Naziv: ");

        jLabel2.setText("Opis: ");

        areaOpis.setColumns(20);
        areaOpis.setRows(5);
        jScrollPane1.setViewportView(areaOpis);

        btnKreirajZadatak.setText("Kreiraj zadatak");
        btnKreirajZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajZadatakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKreirajZadatak)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajZadatak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajZadatakActionPerformed
        String naziv = txtNaziv.getText();
        String opis = areaOpis.getText();

        if (naziv.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Morate uneti naziv zadatka!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Zadatak zad = new Zadatak(naziv, opis, projekat);

        try {
            KlijentKontroler.getInstance().zapamtiZadatak(zad);
            parentForma.popuniKomponente();
            this.dispose();
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio zadatak!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze zapamtiti zadatak!", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormaKreiranjeZadatka.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnKreirajZadatakActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaOpis;
    private javax.swing.JButton btnKreirajZadatak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
