/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme_projekat;

import logika.KlijentKontroler;
import domen.Projekat;
import domen.Zaduzenje;
import domen.Zaposleni;
import forme.PocetnaForma;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author relja
 */
public class FormaKreiranjeProjekta extends javax.swing.JFrame {

    /**
     * Creates new form FormaNoviProjekat
     */
    Zaposleni zaposleni;
    Projekat projekat;
    PocetnaForma parentForma;

    public FormaKreiranjeProjekta(PocetnaForma parentForma, Zaposleni zaposleni) {
        setAlwaysOnTop(true);
        this.parentForma = parentForma;
        this.zaposleni = zaposleni;
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        podesiKomponente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNazivProjekta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaKratakOpis = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnKreirajProjekat = new javax.swing.JButton();
        JXDatePicker = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreiranje projekta");

        jLabel1.setText("Naziv projekta: ");

        jLabel2.setText("Kratak opis:");

        areaKratakOpis.setColumns(20);
        areaKratakOpis.setRows(5);
        jScrollPane1.setViewportView(areaKratakOpis);

        jLabel3.setText("Datum pocetka: ");

        btnKreirajProjekat.setText("Kreiraj projekat");
        btnKreirajProjekat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajProjekatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(txtNazivProjekta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JXDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKreirajProjekat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JXDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKreirajProjekat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajProjekatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajProjekatActionPerformed
        projekat = new Projekat();

        Date datum = JXDatePicker.getDate();

        if (txtNazivProjekta.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Morate uneti naziv projekta!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (datum == null) {
            JOptionPane.showMessageDialog(null, "Morate uneti datum pocetka projekta iz padajuce liste!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate datumLD = datum.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        projekat.setDatumPocetka(datumLD);
        projekat.setNaziv(txtNazivProjekta.getText());
        projekat.setOpis(areaKratakOpis.getText());
        projekat.setKompanija(this.zaposleni.getKompanija());

        try {
            KlijentKontroler.getInstance().zapamtiProjekat(projekat);

            parentForma.popuniTabelu();

            dispose();
            JOptionPane.showMessageDialog(null, "Sistem je zapamtio projekat!", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze zapamtiti projekat!", "Greska", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(FormaKreiranjeProjekta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnKreirajProjekatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker JXDatePicker;
    private javax.swing.JTextArea areaKratakOpis;
    private javax.swing.JButton btnKreirajProjekat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNazivProjekta;
    // End of variables declaration//GEN-END:variables

    private void podesiKomponente() {
        JXDatePicker.getEditor().setText("Unesi datum iz padajuce liste desno!");
        JXDatePicker.getEditor().setEnabled(false);
        areaKratakOpis.setLineWrap(true);
        areaKratakOpis.setWrapStyleWord(true);
    }
}
